name: jeevandesk_flutter
description: "A new Flutter project."

publish_to: 'none' # This prevents publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  video_player: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/splash/thunder_splash.mp4

  # Enable this later when you add Manrope font
  # fonts:
  #   - family: Manrope
  #     fonts:
  #       - asset: assets/fonts/Manrope-Regular.ttf
  #       - asset: assets/fonts/Manrope-Bold.ttf
  #         weight: 700
